#!/bin/sh

chown -R Debian-exim:Debian-exim /var/spool/exim4
chown -R Debian-exim /var/log/exim4
rm /var/log/exim4/paniclog
/etc/init.d/exim4 restart

/etc/init.d/ssh restart
/usr/local/sbin/apt-update

tail /var/log/exim4/mainlog
